/**
 * Default Models Configuration
 * Shared models displayed across the application
 */

import { ReplicateModel } from "@/lib/types";

export const DEFAULT_MODELS: ReplicateModel[] = [
  {
    owner: "tylerbishopdev",
    name: "tyler",
    description: "Tyler model for advanced generation",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/tylerbishopdev/tyler",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: null,
    },
  },
  {
    owner: "tylerbishopdev",
    name: "dotmatrix",
    description: "Dot matrix style generation model",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/tylerbishopdev/dotmatrix",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: null,
    },
  },
  {
    owner: "meta",
    name: "sam-2-video",
    description: "Segment Anything Model 2 for video segmentation",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/meta/sam-2-video",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: null,
    },
  },
  {
    owner: "google",
    name: "nano-banana",
    description: "Lightweight and efficient model by Google",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/google/nano-banana",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: null,
    },
  },
  {
    owner: "runwayml",
    name: "gen4-aleph",
    description: "Generation 4 Aleph model for advanced synthesis",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/runwayml/gen4-aleph",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: null,
    },
  },
  {
    owner: "runwayml",
    name: "gen4-turbo",
    description: "Fast generation with Gen4 Turbo",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/runwayml/gen4-turbo",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: null,
    },
  },
  {
    owner: "tencent",
    name: "hunyuan3d-2mv",
    description: "3D generation from 2 multi-view images",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/tencent/hunyuan3d-2mv",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: null,
    },
  },
  {
    owner: "adirik",
    name: "text2tex",
    description: "Generate textures from text descriptions",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/adirik/text2tex",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: null,
    },
  },
  {
    owner: "zsxkib",
    name: "create-rvc-dataset",
    description: "Create RVC datasets for voice conversion",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/zsxkib/create-rvc-dataset",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: null,
    },
  },
  {
    owner: "black-forest-labs",
    name: "flux-kontext-pro",
    description: "FLUX Kontext Pro for advanced image generation",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/black-forest-labs/flux-kontext-pro",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: null,
    },
  },
  {
    owner: "black-forest-labs",
    name: "flux-kontext-max",
    description: "FLUX Kontext Max - Maximum quality generation",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/black-forest-labs/flux-kontext-max",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: null,
    },
  },
  {
    owner: "black-forest-labs",
    name: "flux-1.1-pro",
    description: "FLUX 1.1 Professional image generation",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/black-forest-labs/flux-1.1-pro",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: null,
    },
  },
  {
    owner: "black-forest-labs",
    name: "flux-1.1-pro-ultra",
    description: "FLUX 1.1 Pro Ultra - highest quality generation",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/black-forest-labs/flux-1.1-pro-ultra",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: null,
    },
  },
  {
    owner: "black-forest-labs",
    name: "flux-dev",
    description: "FLUX Development version for testing",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/black-forest-labs/flux-dev",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: null,
    },
  },
  {
    owner: "black-forest-labs",
    name: "flux-schnell",
    description: "FLUX Schnell - Fast image generation",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/black-forest-labs/flux-schnell",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: null,
    },
  },
  {
    owner: "black-forest-labs",
    name: "flux-pro",
    description: "FLUX Pro for professional image generation",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/black-forest-labs/flux-pro",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: null,
    },
  },
  {
    owner: "black-forest-labs",
    name: "flux-fill-pro",
    description: "FLUX Fill Pro for inpainting and outpainting",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/black-forest-labs/flux-fill-pro",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: null,
    },
  },
  {
    owner: "bytedance",
    name: "seedream-4",
    description: "SeeDream 4 for creative image synthesis",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/bytedance/seedream-4",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: null,
    },
  },
  {
    owner: "google",
    name: "veo-3-fast",
    description: "Google Veo 3 Fast - Quick video generation",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/google/veo-3-fast",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: null,
    },
  },
];

// Group models by owner for better organization
export const GROUPED_MODELS = DEFAULT_MODELS.reduce((acc, model) => {
  if (!acc[model.owner]) {
    acc[model.owner] = [];
  }
  acc[model.owner].push(model);
  return acc;
}, {} as Record<string, ReplicateModel[]>);

// Get model display name (shortened for sidebar)
export const getModelDisplayName = (model: ReplicateModel): string => {
  return model.name
    .replace(/^flux-/, "")
    .replace(/^gen4-/, "")
    .replace(/^veo-/, "");
};
