/**
 * Default Models Configuration
 * Shared models displayed across the application
 */

import { ReplicateModel } from "@/lib/types";

export const DEFAULT_MODELS: ReplicateModel[] = [
  {
    owner: "tylerbishopdev",
    name: "tyler",
    description: "Tyler model for advanced generation",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "tylerbishopdev/tyler:01ce0a0fdc7a46ec74a3c093f6163c5a5f633297a06514229e8775c877507643",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
  {
    owner: "tylerbishopdev",
    name: "dotmatrix",
    description: "Dot matrix style generation model",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/tylerbishopdev/dotmatrix",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
  {
    owner: "meta",
    name: "sam-2-video",
    description: "Segment Anything Model 2 for video segmentation",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/meta/sam-2-video",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
  {
    owner: "google",
    name: "nano-banana",
    description: "Lightweight and efficient model by Google",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/google/nano-banana",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
  {
    owner: "runwayml",
    name: "gen4-aleph",
    description: "Generation 4 Aleph model for advanced synthesis",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/runwayml/gen4-aleph",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
  {
    owner: "runwayml",
    name: "gen4-turbo",
    description: "Fast generation with Gen4 Turbo",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/runwayml/gen4-turbo",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
  {
    owner: "tencent",
    name: "hunyuan3d-2mv",
    description: "3D generation from 2 multi-view images",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/tencent/hunyuan3d-2mv",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
  {
    owner: "adirik",
    name: "text2tex",
    description: "Generate textures from text descriptions",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/adirik/text2tex",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
  {
    owner: "zsxkib",
    name: "create-rvc-dataset",
    description: "Create RVC datasets for voice conversion",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/zsxkib/create-rvc-dataset",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
  {
    owner: "black-forest-labs",
    name: "flux-kontext-pro",
    description: "FLUX Kontext Pro for advanced image generation",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/black-forest-labs/flux-kontext-pro",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
  {
    owner: "black-forest-labs",
    name: "flux-kontext-max",
    description: "FLUX Kontext Max - Maximum quality generation",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/black-forest-labs/flux-kontext-max",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
  {
    owner: "black-forest-labs",
    name: "flux-1.1-pro",
    description: "FLUX 1.1 Professional image generation",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/black-forest-labs/flux-1.1-pro",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
  {
    owner: "black-forest-labs",
    name: "flux-1.1-pro-ultra",
    description: "FLUX 1.1 Pro Ultra - highest quality generation",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/black-forest-labs/flux-1.1-pro-ultra",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
  {
    owner: "black-forest-labs",
    name: "flux-dev",
    description: "FLUX Development version for testing",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/black-forest-labs/flux-dev",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
  {
    owner: "black-forest-labs",
    name: "flux-schnell",
    description: "FLUX Schnell - Fast image generation",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/black-forest-labs/flux-schnell",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
  {
    owner: "black-forest-labs",
    name: "flux-pro",
    description: "FLUX Pro for professional image generation",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/black-forest-labs/flux-pro",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
  {
    owner: "black-forest-labs",
    name: "flux-fill-pro",
    description: "FLUX Fill Pro for inpainting and outpainting",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/black-forest-labs/flux-fill-pro",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
  {
    owner: "bytedance",
    name: "seedream-4",
    description: "SeeDream 4 for creative image synthesis",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/bytedance/seedream-4",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
  {
    owner: "google",
    name: "veo-3",
    description: "Google's flagship Veo 3 text to video model, with audio",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/google/veo-3",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
  {
    owner: "google",
    name: "veo-3-fast",
    description:
      "A faster and cheaper version of Google's Veo 3 video model, with audio",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/google/veo-3-fast",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
  {
    owner: "google",
    name: "imagen-4",
    description: "Google's Imagen 4 flagship model",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/google/imagen-4",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
  {
    owner: "google",
    name: "imagen-4-fast",
    description:
      "Use this fast version of Imagen 4 when speed and cost are more important than quality",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/google/imagen-4-fast",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
  {
    owner: "google",
    name: "imagen-4-ultra",
    description:
      "Use this ultra version of Imagen 4 when quality matters more than speed and cost",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/google/imagen-4-ultra",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
  {
    owner: "minimax",
    name: "video-01",
    description: "Generate 6s videos with prompts or images (Hailuo)",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/minimax/video-01",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
  {
    owner: "recraft-ai",
    name: "recraft-v3",
    description:
      "Recraft V3 (red_panda) text-to-image model with long text generation",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/recraft-ai/recraft-v3",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
  {
    owner: "ideogram-ai",
    name: "ideogram-v3-turbo",
    description:
      "Fastest and cheapest Ideogram v3 - stunning realism and creative designs",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/ideogram-ai/ideogram-v3-turbo",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
  {
    owner: "ideogram-ai",
    name: "ideogram-v3-balanced",
    description:
      "Balance speed, quality and cost - stunning realism and creative designs",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/ideogram-ai/ideogram-v3-balanced",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
  {
    owner: "ideogram-ai",
    name: "ideogram-v3-quality",
    description:
      "Highest quality Ideogram v3 - stunning realism and creative designs",
    visibility: "public",
    run_count: 0,
    cover_image_url: "",
    github_url: "",
    paper_url: "",
    license_url: "",
    url: "https://replicate.com/ideogram-ai/ideogram-v3-quality",
    latest_version: {
      id: "",
      created_at: new Date().toISOString(),
      cog_version: "",
      openapi_schema: undefined,
    },
  },
];

// Group models by owner for better organization
export const GROUPED_MODELS = DEFAULT_MODELS.reduce((acc, model) => {
  if (!acc[model.owner]) {
    acc[model.owner] = [];
  }
  acc[model.owner].push(model);
  return acc;
}, {} as Record<string, ReplicateModel[]>);

// Get model display name (shortened for sidebar)
export const getModelDisplayName = (model: ReplicateModel): string => {
  return model.name
    .replace(/^flux-/, "")
    .replace(/^gen4-/, "")
    .replace(/^veo-/, "")
    .replace(/^imagen-/, "")
    .replace(/^ideogram-/, "")
    .replace(/^video-/, "")
    .replace(/^recraft-/, "");
};
